# Utiliser l'image Jenkins officielle comme base
FROM jenkins/jenkins:lts-jdk11

# Passer à l'utilisateur root pour installer des paquets
USER root

# Installer le client Docker et les utilitaires NVIDIA en une seule passe
RUN apt-get update && apt-get install -y \
    lsb-release \
    nvidia-utils \
    && curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
    https://download.docker.com/linux/debian/gpg \
    && echo "deb [arch=$(dpkg --print-architecture) \
    signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
    https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get update && apt-get install -y docker-ce-cli \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Revenir à l'utilisateur jenkins par défaut
USER jenkins 