# On peut supprimer la version, comme le suggère l'avertissement
services:
  jenkins:
    # --- MODIFICATION CLÉ ---
    # Au lieu de 'image:', on utilise 'build:'.
    build: . # Le '.' signifie 'construire en utilisant le Dockerfile dans le dossier actuel'
    container_name: jenkins
    
    network_mode: "host"

    privileged: true
    user: root
    
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
volumes:
  jenkins_data: {}