name: YOLO Model Training Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test
    paths:
      - "dataset/**"
      - "mlops/scripts/**"
      - ".github/workflows/training_pipeline.yml"

jobs:
  train-and-evaluate-model:
    runs-on: ubuntu-latest

    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # --- Étape avec indentation corrigée ---
      - name: Free up disk space on the runner
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: "true"
          remove-haskell: "true"
          remove-android: "true"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # --- Étape de Caching (Très importante) ---
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up DVC
        uses: iterative/dvc-action@v1

      - name: Pull data from DVC (Azure) remote
        run: dvc pull -r myremote

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
          pip install -r server/requirements.txt
          pip install mlflow PyYAML

      - name: Run model training script
        id: training_step
        run: |
          output=$(python mlops/scripts/train.py --epochs 10 --batch 8 --data dataset/samurai/data.yaml --model yolov8s)
          echo "$output"
          run_id=$(echo "$output" | grep 'MLflow Run ID:' | awk '{print $4}')
          echo "run_id=$run_id" >> $GITHUB_OUTPUT

      - name: Compare new model with production model
        id: comparison_step
        run: |
          python mlops/scripts/compare_models.py --run_id ${{ steps.training_step.outputs.run_id }}
          result=$(cat comparison_result.txt)
          echo "is_better=$result" >> $GITHUB_OUTPUT

      - name: Create GitHub Release with New Model
        if: ${{ steps.comparison_step.outputs.is_better == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_number }}
          name: Model Release ${{ github.run_number }}
          body: |
            New version of the YOLO model trained by GitHub Actions.
            - Run ID: ${{ steps.training_step.outputs.run_id }}
          files: |
            runs/detect/**/weights/best.onnx

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-tracking-results
          path: mlruns/
