name: YOLO Model Training Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test
    paths:
      - "dataset/**"
      - "mlops/scripts/**"
      - ".github/workflows/training_pipeline.yml"

jobs:
  train-and-evaluate-model:
    runs-on: ubuntu-latest

    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Pull data from DVC (Azure) remote
        run: dvc pull -r myremote

      - name: Pull data from DVC (Azure) remote
        run: dvc pull -r myremote

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          pip install mlflow PyYAML # S'assurer que ces dépendances sont là

      - name: Run model training script
        id: training_step
        run: |
          output=$(python mlops/scripts/train.py --epochs 10 --batch 8 --data dataset/samurai/data.yaml --model yolov8s)
          echo "$output"
          run_id=$(echo "$output" | grep 'MLflow Run ID:' | awk '{print $4}')
          echo "run_id=$run_id" >> $GITHUB_OUTPUT

      - name: Compare new model with production model
        id: comparison_step
        run: |
          python mlops/scripts/compare_models.py --run_id ${{ steps.training_step.outputs.run_id }}
          result=$(cat comparison_result.txt)
          echo "is_better=$result" >> $GITHUB_OUTPUT

      - name: Deploy model if it is better
        if: ${{ steps.comparison_step.outputs.is_better == 'true' }}
        run: |
          echo "🚀 DEPLOYMENT TRIGGERED! 🚀"
          echo "The new model with Run ID ${{ steps.training_step.outputs.run_id }} is better and would be deployed now."

      - name: Do not deploy if model is not better
        if: ${{ steps.comparison_step.outputs.is_better == 'false' }}
        run: |
          echo "🛑 Deployment skipped. The new model is not better than the production version."

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-tracking-results
          path: mlruns/
